routes/web.php
<?php

use App\Http\Controllers\Member\ProductController;
use App\Http\Controllers\Member\ProfileContactInformationController;
use App\Http\Controllers\Member\ProfileController;
use App\Http\Controllers\Member\ProfilePasswordController;
use App\Http\Controllers\ProductPhotoController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::middleware(['auth', 'verified'])->group(function () {
    Route::prefix('profile')->group(function () {
        Route::get('', [ProfileController::class, 'index'])->name('profile.index');
        Route::get('edit', [ProfileController::class, 'edit'])->name('profile.edit');
        Route::patch('', [ProfileController::class, 'update'])->name('profile.update');

        Route::get('help', function () {
            return view('profile/help');
        });
        Route::get('password/edit', [ProfilePasswordController::class, 'edit'])->name('profile.password.edit');
        Route::patch('password', [ProfilePasswordController::class, 'update'])->name('profile.password.update');

        Route::get('contact-information/edit', [ProfileContactInformationController::class, 'edit'])->name('profile.contact-information.edit');
        Route::patch('contact-information', [ProfileContactInformationController::class, 'update'])->name('profile.contact-information.update');

    });

    Route::resource('product-photo', ProductPhotoController::class)->only(['store','destroy']);
    Route::get("product/get-subcategories/{categoryId}", [ProductController::class, 'getSubCategories']);
    Route::get("product", [ProductController::class, 'index'])->name('product.index');
    Route::resource("product", ProductController::class);

});


require __DIR__ . '/auth.php';

resources/views/header/nav.blade.php
<div class="w-100">
    <nav class="navbar navbar-expand-lg navbar-dark bg-brand-gray-1" id="HeaderNav">
        <div class="container">
            <a class="navbar-brand" href="#"><img src="{{ asset('img/brand-logo-white.png') }}" width="33px" height="32.5px" class="" /></a>
            <div class="collapse navbar-collapse nav-links" >
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="#">Buy Equipment</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route("product.index") }}">Sell Equipment</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Rent Equipment</a>
                    </li>
                </ul>
            </div>
            <div id="signup_cont" class="expand">
                <div class="d-flex justify-content-end me-3 me-xl-0 justify-content-xxl-center align-items-end align-items-xxl-start h-100 flex-column">
                    <div class="d-flex align-items-center flex-row position-relative">
                        @if(!\Auth::guard('member')->check())
                        <a class="text-white align-self-center text-decoration-none" href="{{ route('login') }}">Login</a>
                        <a class="ms-3 text-white align-self-center text-decoration-none" href="{{ route('register') }}">Sign Up</a>
                        @else
                            <a href="javascript:;" class="user-panel-toggle"><i class="fas fa-bars"></i></a>
                        @endif
                        <div class="user-panel desktop">
                            <a href="{{ route('profile.index') }}" class="btn d-block btn-link text-white align-self-center text-decoration-none">Profile</a>
                            <a href="{{ route('profile.edit') }}" class="btn d-block btn-link text-white align-self-center text-decoration-none">Settings</a>
                            <button type="button" class="btn btnLogout w-100 d-block btn-link text-white align-self-center text-decoration-none">Logout</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </nav>
</div>

resources/views/header/search.blade.php
<div class="w-100">
    <div class="container">
        <div class="row">
            <div class="d-none d-lg-flex col-12 col-lg-4 col-xl-3 pe-xl-0 my-3 justify-content-start align-items-center">
                <img src="{{ asset('img/brand-logo.png') }}" width="38px" height="37.75px" class="ms-1 me-3" />
                <img src="{{ asset('img/brand-name.png') }}" style="max-height:37.5px;" class="img-fluid" />
            </div>
            <div class="col-10 col-sm-9 col-md-10 col-lg-6 col-xl-8 my-3 justify-content-center justify-content-md-start justify-content-lg-end d-flex">
                <form name="formSearch" class="row w-100">
                    @csrf
                    <div class="col-11 gx-0 gx-xl-5">
                        <div class=" input-group input-group-header-search">
                            <input type="text" class="form-control" name="search" placeholder="" aria-label="" aria-describedby="button-addon2">
                            <button class="btn btn-outline-secondary btn-header-search" type="button" id="button-addon2"><i class="fas fa-search"></i></button>
                        </div>
                    </div>
                </form>
            </div>
            <div class="col-2 col-sm-3 col-md-2 col-lg-2 col-xl-1 my-3 justify-content-end d-flex align-items-center">
                @if(\Auth::guard('member')->check())
                <a href="{{ route("product.create") }}" class="btn d-block d-md-inline px-2 px-sm-4 px-lg-5 bg-brand-yellow-1 text-white">Sell</a>
                @endif
            </div>
        </div>
        <div class="row">
            <div class="col">
                <hr class="mb-0">
            </div>
        </div>
    </div>
</div>